### ISSUE TITLE
Best practice for "inplace" sort() method on MutRrbt

### ISSUE THREAD

**Issue by axkr** [GlenKPeterson/Paguro#48]
Sorting a `MutRrbt` "inplace" is a very common process in my project.
What is the "best practice" for sorting a `MutRrbt` data structure (before making it `immutable()`)?

Should something simple like the following snippet directly be included in  `MutRrbt` or can this be done in a more "clever" way?

```java
  public static MutRrbt<Object> sort(MutRrbt<Object> rrbTree, int fromIndex, int toIndex,
      Comparator<Object> comparator) {
    int size = rrbTree.size();
    Object[] a = new Object[size];
    rrbTree.toArray(a);
    Arrays.sort(a, fromIndex, toIndex, comparator);
    return StaticImports.mutableRrb(a);
  }
```

**Comment by GlenKPeterson** [comment]
This question deserves careful thought and I'm busy with holiday stuff right now.  The quick answer is that if you don't have duplicates, use the [PersistentTreeSet](https://github.com/GlenKPeterson/Paguro/blob/master/src/main/java/org/organicdesign/fp/collections/PersistentTreeSet.java) or [sortedSet()](https://github.com/GlenKPeterson/Paguro/blob/master/src/main/java/org/organicdesign/fp/StaticImports.java#L234) instead of an RRB-Tree.

Otherwise, your solution looks correct.  That's the right place to start.  We can try to improve efficiency later.

**Comment by axkr** [comment]
> The quick answer is that if you don't have duplicates, use the [PersistentTreeSet](https://github.com/GlenKPeterson/Paguro/blob/master/src/main/java/org/organicdesign/fp/collections/PersistentTreeSet.java) or [sortedSet()](https://github.com/GlenKPeterson/Paguro/blob/master/src/main/java/org/organicdesign/fp/StaticImports.java#L234) instead of an RRB-Tree.

I have duplicates and another data structure is not an option.
